import { boolean, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";

export const projectStatus = pgEnum("project_status", ["draft", "ready", "publishing", "published", "failed", "archived"]);
export const jobStatus = pgEnum("job_status", ["queued", "running", "succeeded", "failed", "cancelled"]);
export const documentationKind = pgEnum("documentation_kind", ["readme", "project_summary"]);

export const users = pgTable("users", { id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 160 }), email: varchar("email", { length: 320 }).notNull().unique(), image: text("image"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const accounts = pgTable("accounts", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), provider: varchar("provider", { length: 64 }).notNull(), providerAccountId: varchar("provider_account_id", { length: 255 }).notNull(), type: varchar("type", { length: 32 }).notNull(), accessToken: text("access_token"), refreshToken: text("refresh_token"), expiresAt: integer("expires_at"), scope: text("scope") }, (t) => [uniqueIndex("accounts_provider_account_idx").on(t.provider, t.providerAccountId), index("accounts_user_idx").on(t.userId)]);
export const sessions = pgTable("sessions", { id: uuid("id").defaultRandom().primaryKey(), sessionToken: varchar("session_token", { length: 255 }).notNull().unique(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), expires: timestamp("expires", { withTimezone: true }).notNull() });
export const projects = pgTable("projects", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), name: varchar("name", { length: 100 }).notNull(), slug: varchar("slug", { length: 100 }).notNull(), description: text("description"), projectType: varchar("project_type", { length: 32 }).notNull().default("development"), status: projectStatus("status").notNull().default("draft"), visibility: varchar("visibility", { length: 16 }).notNull().default("private"), defaultBranch: varchar("default_branch", { length: 100 }).notNull().default("main"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(), archivedAt: timestamp("archived_at", { withTimezone: true }) }, (t) => [uniqueIndex("projects_user_slug_idx").on(t.userId, t.slug), index("projects_user_idx").on(t.userId)]);
export const projectFiles = pgTable("project_files", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), path: text("path").notNull(), blobUrl: text("blob_url").notNull(), contentType: varchar("content_type", { length: 160 }).notNull(), sizeBytes: integer("size_bytes").notNull(), sha256: varchar("sha256", { length: 64 }).notNull(), isText: boolean("is_text").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("project_files_path_idx").on(t.projectId, t.path), index("project_files_project_idx").on(t.projectId)]);
export const githubRepositories = pgTable("github_repositories", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").notNull().unique().references(() => projects.id, { onDelete: "cascade" }), githubRepositoryId: varchar("github_repository_id", { length: 64 }).notNull().unique(), owner: varchar("owner", { length: 100 }).notNull(), name: varchar("name", { length: 100 }).notNull(), htmlUrl: text("html_url").notNull(), defaultBranch: varchar("default_branch", { length: 100 }).notNull(), visibility: varchar("visibility", { length: 16 }).notNull(), pushedAt: timestamp("pushed_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const publishingJobs = pgTable("publishing_jobs", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), status: jobStatus("status").notNull().default("queued"), stage: varchar("stage", { length: 64 }).notNull().default("queued"), progress: integer("progress").notNull().default(0), errorCode: varchar("error_code", { length: 64 }), errorMessage: text("error_message"), idempotencyKey: uuid("idempotency_key").notNull().unique(), startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("publishing_jobs_project_idx").on(t.projectId, t.createdAt)]);
export const generatedDocuments = pgTable("generated_documents", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), kind: documentationKind("kind").notNull(), content: text("content").notNull(), model: varchar("model", { length: 100 }), sourceFileCount: integer("source_file_count").notNull().default(0), metadata: jsonb("metadata").notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("generated_documents_project_idx").on(t.projectId, t.kind)]);
